### ISSUE TITLE
[BUG] Trying to access array offset on value of type null with PHP 8.0 or PHP 8.1

### ISSUE THREAD

**Issue by bh-teufels** [pixelant/demander#21]
**Describe the bug**
On Typo3 11.5 with PHP 8.0 & PHP 8.1 following Error appears

#1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Trying to access array offset on value of type null in /app/web/typo3conf/ext/demander/Classes/Middlewares/DemanderRequestMiddleware.php line 17

**To Reproduce**

1. Use 'pxa_product_manager' which requires 'demander' with PHP 8.0 or PHP 8.1

**Expected behavior**
Possibility to use 'pxa_product_manager' and 'demander' with  PHP 8.0 and PHP 8.1

**Screenshots**
![Bildschirmfoto 2022-08-09 um 10 24 54](https://user-images.githubusercontent.com/38100744/183602685-93b2fd51-cee6-4a0b-8e86-bf4d240416c1.png)

**Environement:**
- TYPO3: 11.5.14
- PHP: 8.1.2
- pxa_product_manager: v11.0.6
- demander: 0.2.0

**Additional context**
don't know if  'pxa_product_manager' works with PHP 8.0 or PHP 8.1 (Error on 'demander' appears first)

**Comment by ko-je** [comment]
` $demands = $request->getParsedBody();

        if (isset($demands['d'])) {
            RequestSingleton::getInstance()->setRequest($request);
        }`
